services:
  postgres:
#    image: postgres:alpine
    image: postgis/postgis:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-db
