services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-db
  kafka:
    image: confluentinc/confluent-local
    ports:
      - '9092:9092'
