// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresgen

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	DeleteOrganization(ctx context.Context, organizationID string) error
	DeleteOrganizationByName(ctx context.Context, name string) error
	ExistOrganizationByName(ctx context.Context, name string) (bool, error)
	GetOrganizationByID(ctx context.Context, organizationID string) (Organization, error)
	HasMorePagesOrganizationList(ctx context.Context, arg HasMorePagesOrganizationListParams) (HasMorePagesOrganizationListRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
